---
- hosts: Server

  tasks:
# copy current bashrc to .bak 
  - name: backup bashrc
    become: true
    file:
      src: /home/freaky/.bashrc
      dest: /home/freaky/.bashrc.bak
      state: hard
      
# copy new copy of bashrc
  - name: Download bashrc
    get_url:
      url: https://raw.githubusercontent.com/Freaky2112/Semaphore/main/.bashrc
      dest: "/home/freaky/.bashrc"
      owner: freaky
      group: freaky
      
