---
- hosts: Server

  tasks:
# copy current bashrc to .bak 
  - name: backup bashrc
    become_user: freaky
    ansible.builtin.file:
      src: /home/freaky/.bashrc
      dest: /home/freaky/.bashrc.bak

# copy new copy of bashrc
  - name: Download bashrc
    get_url:
      url: https://github.com/Freaky2112/Semaphore/blob/main/.bashrc
      dest: "/home/freaky/.bashrc"
      owner: freaky
      group: freaky
      

#- name: Rename a file on remote systems
#  ansible.builtin.file:
#    src: /path/to/original_file.txt
#    dest: /path/to/renamed_file.txt
#    state: link
#    force: yes
