---
- hosts: Server
  become: true

  pre_tasks:
    - name: update repositories
      package:
        update_cache: yes
      changed_when: False
  tasks:    
    - name: Do Distro Upgrade
      tags: upgrade
      become: true
      # ansible.builtin.apt:
      apt: upgrade=dist force_apt_get=yes
       # state: latest
       # upgrade: dist
      when: ansible_distribution == 'Ubuntu'

# remove dependencies
    - name: Remove dependencies that are no longer required.
      ansible.builtin.apt:
        autoremove: yes
