---
- hosts: all
  become: true

  pre_tasks:
    - name: update repositories
      package:
        update_cache: yes
      changed_when: False
  tasks:    
    - name: Do Distro Upgrade
      tags: upgrade
      become: true
      ansible.builtin.apt:
        upgrade: dist
        # update_cache: yes
      when: ansible_distribution == 'Ubuntu' or ansible_distribution =='Raspbian' or ansible_distribution =='Debian'


# remove dependencies
    - name: Remove dependencies that are no longer required.
      ansible.builtin.apt:
        autoremove: yes

# sending a message
#- name: Send Hello World! to the webhook
#  discord_webhook:
#    webhook_url: https://discord.com/api/webhooks/1269518205370765312/1U_Z_N44wWZA8JC4K2rdzYKCKXy1KJRbADdycm2XF3Fol6-9j_RuS_HxwrA4fmF1zCSG
#    content: Hello, world!




        
